/* Autogenerated header file to show build variables used in system */
#ifndef __BUILD_AUTOGEN_H
#define __BUILD_AUTOGEN_H
#define HAS_GIT_PARAMS

#define BUILD_PATH	"C:\\Users\\chris\\Desktop\\beaumont\\penetrometer\r\n\0"

#define BUILD_SYSTEM	"PIZZABOX\r\n\0"

#define BUILD_USER_DOMAIN	"PIZZABOX\r\n\0"

#define BUILD_USER_NAME	"chris\r\n\0"

#define BRANCH_NAME	"master\r\n\0"

#define COMMIT_SHA	"7a321bd4e782d83cd4f9517ae1152cd1a38f40c1\r\n\0"

/* Time format: YYYY_MM_DD_HH:mm:ss */
#define LAST_COMMIT_TIME_UTC	"2015_01_29_08:44:52\r\n\0"

#define COMPILE_TIME_UTC	"2015_01_31_00:17:35\r\n\0"

#define COMPILE_TIME_UTC_YYYY	2015

#define COMPILE_TIME_UTC_MM	1

#define COMPILE_TIME_UTC_DD	31

#define COMPILE_TIME_UTC_HH	0

#define COMPILE_TIME_UTC_mm	17

#define COMPILE_TIME_UTC_ss	35

#define LONGEST_STR_USED	44

extern int BuildPathLength;
extern int BuildSystemLength;
extern int BuildUserDomainLength;
extern int BuildUserNameLength;
extern int BuildBranchNameLength;
extern int BuildCommitSHALength;
extern int LastCommitTimeLength;
extern int CompileTimeLength;
#endif

