/* Created by C Chock - Beaumont - autogenerated with MATLAB code
 * create_chars.m */
#include "vis.h"
uint8* get_char_graphic_pointer(char char_to_place){
    uint8* rtnval = 0;
    switch(char_to_place){
    case 33:
        rtnval = (uint8*) __char_33;
        __HELV_b_cur_wid = __char_wid_33;
        __HELV_b_cur_lstart = __char_lstart_33;
        __HELV_b_cur_height = __char_height_33;
        __HELV_b_cur_top = __char_top_33;
        __HELV_b_cur_bottom = __char_bottom_33;
        break;
    case 34:
        rtnval = (uint8*) __char_34;
        __HELV_b_cur_wid = __char_wid_34;
        __HELV_b_cur_lstart = __char_lstart_34;
        __HELV_b_cur_height = __char_height_34;
        __HELV_b_cur_top = __char_top_34;
        __HELV_b_cur_bottom = __char_bottom_34;
        break;
    case 35:
        rtnval = (uint8*) __char_35;
        __HELV_b_cur_wid = __char_wid_35;
        __HELV_b_cur_lstart = __char_lstart_35;
        __HELV_b_cur_height = __char_height_35;
        __HELV_b_cur_top = __char_top_35;
        __HELV_b_cur_bottom = __char_bottom_35;
        break;
    case 36:
        rtnval = (uint8*) __char_36;
        __HELV_b_cur_wid = __char_wid_36;
        __HELV_b_cur_lstart = __char_lstart_36;
        __HELV_b_cur_height = __char_height_36;
        __HELV_b_cur_top = __char_top_36;
        __HELV_b_cur_bottom = __char_bottom_36;
        break;
    case 37:
        rtnval = (uint8*) __char_37;
        __HELV_b_cur_wid = __char_wid_37;
        __HELV_b_cur_lstart = __char_lstart_37;
        __HELV_b_cur_height = __char_height_37;
        __HELV_b_cur_top = __char_top_37;
        __HELV_b_cur_bottom = __char_bottom_37;
        break;
    case 38:
        rtnval = (uint8*) __char_38;
        __HELV_b_cur_wid = __char_wid_38;
        __HELV_b_cur_lstart = __char_lstart_38;
        __HELV_b_cur_height = __char_height_38;
        __HELV_b_cur_top = __char_top_38;
        __HELV_b_cur_bottom = __char_bottom_38;
        break;
    case 39:
        rtnval = (uint8*) __char_39;
        __HELV_b_cur_wid = __char_wid_39;
        __HELV_b_cur_lstart = __char_lstart_39;
        __HELV_b_cur_height = __char_height_39;
        __HELV_b_cur_top = __char_top_39;
        __HELV_b_cur_bottom = __char_bottom_39;
        break;
    case 40:
        rtnval = (uint8*) __char_40;
        __HELV_b_cur_wid = __char_wid_40;
        __HELV_b_cur_lstart = __char_lstart_40;
        __HELV_b_cur_height = __char_height_40;
        __HELV_b_cur_top = __char_top_40;
        __HELV_b_cur_bottom = __char_bottom_40;
        break;
    case 41:
        rtnval = (uint8*) __char_41;
        __HELV_b_cur_wid = __char_wid_41;
        __HELV_b_cur_lstart = __char_lstart_41;
        __HELV_b_cur_height = __char_height_41;
        __HELV_b_cur_top = __char_top_41;
        __HELV_b_cur_bottom = __char_bottom_41;
        break;
    case 42:
        rtnval = (uint8*) __char_42;
        __HELV_b_cur_wid = __char_wid_42;
        __HELV_b_cur_lstart = __char_lstart_42;
        __HELV_b_cur_height = __char_height_42;
        __HELV_b_cur_top = __char_top_42;
        __HELV_b_cur_bottom = __char_bottom_42;
        break;
    case 43:
        rtnval = (uint8*) __char_43;
        __HELV_b_cur_wid = __char_wid_43;
        __HELV_b_cur_lstart = __char_lstart_43;
        __HELV_b_cur_height = __char_height_43;
        __HELV_b_cur_top = __char_top_43;
        __HELV_b_cur_bottom = __char_bottom_43;
        break;
    case 44:
        rtnval = (uint8*) __char_44;
        __HELV_b_cur_wid = __char_wid_44;
        __HELV_b_cur_lstart = __char_lstart_44;
        __HELV_b_cur_height = __char_height_44;
        __HELV_b_cur_top = __char_top_44;
        __HELV_b_cur_bottom = __char_bottom_44;
        break;
    case 45:
        rtnval = (uint8*) __char_45;
        __HELV_b_cur_wid = __char_wid_45;
        __HELV_b_cur_lstart = __char_lstart_45;
        __HELV_b_cur_height = __char_height_45;
        __HELV_b_cur_top = __char_top_45;
        __HELV_b_cur_bottom = __char_bottom_45;
        break;
    case 46:
        rtnval = (uint8*) __char_46;
        __HELV_b_cur_wid = __char_wid_46;
        __HELV_b_cur_lstart = __char_lstart_46;
        __HELV_b_cur_height = __char_height_46;
        __HELV_b_cur_top = __char_top_46;
        __HELV_b_cur_bottom = __char_bottom_46;
        break;
    case 47:
        rtnval = (uint8*) __char_47;
        __HELV_b_cur_wid = __char_wid_47;
        __HELV_b_cur_lstart = __char_lstart_47;
        __HELV_b_cur_height = __char_height_47;
        __HELV_b_cur_top = __char_top_47;
        __HELV_b_cur_bottom = __char_bottom_47;
        break;
    case 48:
        rtnval = (uint8*) __char_48;
        __HELV_b_cur_wid = __char_wid_48;
        __HELV_b_cur_lstart = __char_lstart_48;
        __HELV_b_cur_height = __char_height_48;
        __HELV_b_cur_top = __char_top_48;
        __HELV_b_cur_bottom = __char_bottom_48;
        break;
    case 49:
        rtnval = (uint8*) __char_49;
        __HELV_b_cur_wid = __char_wid_49;
        __HELV_b_cur_lstart = __char_lstart_49;
        __HELV_b_cur_height = __char_height_49;
        __HELV_b_cur_top = __char_top_49;
        __HELV_b_cur_bottom = __char_bottom_49;
        break;
    case 50:
        rtnval = (uint8*) __char_50;
        __HELV_b_cur_wid = __char_wid_50;
        __HELV_b_cur_lstart = __char_lstart_50;
        __HELV_b_cur_height = __char_height_50;
        __HELV_b_cur_top = __char_top_50;
        __HELV_b_cur_bottom = __char_bottom_50;
        break;
    case 51:
        rtnval = (uint8*) __char_51;
        __HELV_b_cur_wid = __char_wid_51;
        __HELV_b_cur_lstart = __char_lstart_51;
        __HELV_b_cur_height = __char_height_51;
        __HELV_b_cur_top = __char_top_51;
        __HELV_b_cur_bottom = __char_bottom_51;
        break;
    case 52:
        rtnval = (uint8*) __char_52;
        __HELV_b_cur_wid = __char_wid_52;
        __HELV_b_cur_lstart = __char_lstart_52;
        __HELV_b_cur_height = __char_height_52;
        __HELV_b_cur_top = __char_top_52;
        __HELV_b_cur_bottom = __char_bottom_52;
        break;
    case 53:
        rtnval = (uint8*) __char_53;
        __HELV_b_cur_wid = __char_wid_53;
        __HELV_b_cur_lstart = __char_lstart_53;
        __HELV_b_cur_height = __char_height_53;
        __HELV_b_cur_top = __char_top_53;
        __HELV_b_cur_bottom = __char_bottom_53;
        break;
    case 54:
        rtnval = (uint8*) __char_54;
        __HELV_b_cur_wid = __char_wid_54;
        __HELV_b_cur_lstart = __char_lstart_54;
        __HELV_b_cur_height = __char_height_54;
        __HELV_b_cur_top = __char_top_54;
        __HELV_b_cur_bottom = __char_bottom_54;
        break;
    case 55:
        rtnval = (uint8*) __char_55;
        __HELV_b_cur_wid = __char_wid_55;
        __HELV_b_cur_lstart = __char_lstart_55;
        __HELV_b_cur_height = __char_height_55;
        __HELV_b_cur_top = __char_top_55;
        __HELV_b_cur_bottom = __char_bottom_55;
        break;
    case 56:
        rtnval = (uint8*) __char_56;
        __HELV_b_cur_wid = __char_wid_56;
        __HELV_b_cur_lstart = __char_lstart_56;
        __HELV_b_cur_height = __char_height_56;
        __HELV_b_cur_top = __char_top_56;
        __HELV_b_cur_bottom = __char_bottom_56;
        break;
    case 57:
        rtnval = (uint8*) __char_57;
        __HELV_b_cur_wid = __char_wid_57;
        __HELV_b_cur_lstart = __char_lstart_57;
        __HELV_b_cur_height = __char_height_57;
        __HELV_b_cur_top = __char_top_57;
        __HELV_b_cur_bottom = __char_bottom_57;
        break;
    case 58:
        rtnval = (uint8*) __char_58;
        __HELV_b_cur_wid = __char_wid_58;
        __HELV_b_cur_lstart = __char_lstart_58;
        __HELV_b_cur_height = __char_height_58;
        __HELV_b_cur_top = __char_top_58;
        __HELV_b_cur_bottom = __char_bottom_58;
        break;
    case 59:
        rtnval = (uint8*) __char_59;
        __HELV_b_cur_wid = __char_wid_59;
        __HELV_b_cur_lstart = __char_lstart_59;
        __HELV_b_cur_height = __char_height_59;
        __HELV_b_cur_top = __char_top_59;
        __HELV_b_cur_bottom = __char_bottom_59;
        break;
    case 60:
        rtnval = (uint8*) __char_60;
        __HELV_b_cur_wid = __char_wid_60;
        __HELV_b_cur_lstart = __char_lstart_60;
        __HELV_b_cur_height = __char_height_60;
        __HELV_b_cur_top = __char_top_60;
        __HELV_b_cur_bottom = __char_bottom_60;
        break;
    case 61:
        rtnval = (uint8*) __char_61;
        __HELV_b_cur_wid = __char_wid_61;
        __HELV_b_cur_lstart = __char_lstart_61;
        __HELV_b_cur_height = __char_height_61;
        __HELV_b_cur_top = __char_top_61;
        __HELV_b_cur_bottom = __char_bottom_61;
        break;
    case 62:
        rtnval = (uint8*) __char_62;
        __HELV_b_cur_wid = __char_wid_62;
        __HELV_b_cur_lstart = __char_lstart_62;
        __HELV_b_cur_height = __char_height_62;
        __HELV_b_cur_top = __char_top_62;
        __HELV_b_cur_bottom = __char_bottom_62;
        break;
    case 63:
        rtnval = (uint8*) __char_63;
        __HELV_b_cur_wid = __char_wid_63;
        __HELV_b_cur_lstart = __char_lstart_63;
        __HELV_b_cur_height = __char_height_63;
        __HELV_b_cur_top = __char_top_63;
        __HELV_b_cur_bottom = __char_bottom_63;
        break;
    case 64:
        rtnval = (uint8*) __char_64;
        __HELV_b_cur_wid = __char_wid_64;
        __HELV_b_cur_lstart = __char_lstart_64;
        __HELV_b_cur_height = __char_height_64;
        __HELV_b_cur_top = __char_top_64;
        __HELV_b_cur_bottom = __char_bottom_64;
        break;
    case 65:
        rtnval = (uint8*) __char_65;
        __HELV_b_cur_wid = __char_wid_65;
        __HELV_b_cur_lstart = __char_lstart_65;
        __HELV_b_cur_height = __char_height_65;
        __HELV_b_cur_top = __char_top_65;
        __HELV_b_cur_bottom = __char_bottom_65;
        break;
    case 66:
        rtnval = (uint8*) __char_66;
        __HELV_b_cur_wid = __char_wid_66;
        __HELV_b_cur_lstart = __char_lstart_66;
        __HELV_b_cur_height = __char_height_66;
        __HELV_b_cur_top = __char_top_66;
        __HELV_b_cur_bottom = __char_bottom_66;
        break;
    case 67:
        rtnval = (uint8*) __char_67;
        __HELV_b_cur_wid = __char_wid_67;
        __HELV_b_cur_lstart = __char_lstart_67;
        __HELV_b_cur_height = __char_height_67;
        __HELV_b_cur_top = __char_top_67;
        __HELV_b_cur_bottom = __char_bottom_67;
        break;
    case 68:
        rtnval = (uint8*) __char_68;
        __HELV_b_cur_wid = __char_wid_68;
        __HELV_b_cur_lstart = __char_lstart_68;
        __HELV_b_cur_height = __char_height_68;
        __HELV_b_cur_top = __char_top_68;
        __HELV_b_cur_bottom = __char_bottom_68;
        break;
    case 69:
        rtnval = (uint8*) __char_69;
        __HELV_b_cur_wid = __char_wid_69;
        __HELV_b_cur_lstart = __char_lstart_69;
        __HELV_b_cur_height = __char_height_69;
        __HELV_b_cur_top = __char_top_69;
        __HELV_b_cur_bottom = __char_bottom_69;
        break;
    case 70:
        rtnval = (uint8*) __char_70;
        __HELV_b_cur_wid = __char_wid_70;
        __HELV_b_cur_lstart = __char_lstart_70;
        __HELV_b_cur_height = __char_height_70;
        __HELV_b_cur_top = __char_top_70;
        __HELV_b_cur_bottom = __char_bottom_70;
        break;
    case 71:
        rtnval = (uint8*) __char_71;
        __HELV_b_cur_wid = __char_wid_71;
        __HELV_b_cur_lstart = __char_lstart_71;
        __HELV_b_cur_height = __char_height_71;
        __HELV_b_cur_top = __char_top_71;
        __HELV_b_cur_bottom = __char_bottom_71;
        break;
    case 72:
        rtnval = (uint8*) __char_72;
        __HELV_b_cur_wid = __char_wid_72;
        __HELV_b_cur_lstart = __char_lstart_72;
        __HELV_b_cur_height = __char_height_72;
        __HELV_b_cur_top = __char_top_72;
        __HELV_b_cur_bottom = __char_bottom_72;
        break;
    case 73:
        rtnval = (uint8*) __char_73;
        __HELV_b_cur_wid = __char_wid_73;
        __HELV_b_cur_lstart = __char_lstart_73;
        __HELV_b_cur_height = __char_height_73;
        __HELV_b_cur_top = __char_top_73;
        __HELV_b_cur_bottom = __char_bottom_73;
        break;
    case 74:
        rtnval = (uint8*) __char_74;
        __HELV_b_cur_wid = __char_wid_74;
        __HELV_b_cur_lstart = __char_lstart_74;
        __HELV_b_cur_height = __char_height_74;
        __HELV_b_cur_top = __char_top_74;
        __HELV_b_cur_bottom = __char_bottom_74;
        break;
    case 75:
        rtnval = (uint8*) __char_75;
        __HELV_b_cur_wid = __char_wid_75;
        __HELV_b_cur_lstart = __char_lstart_75;
        __HELV_b_cur_height = __char_height_75;
        __HELV_b_cur_top = __char_top_75;
        __HELV_b_cur_bottom = __char_bottom_75;
        break;
    case 76:
        rtnval = (uint8*) __char_76;
        __HELV_b_cur_wid = __char_wid_76;
        __HELV_b_cur_lstart = __char_lstart_76;
        __HELV_b_cur_height = __char_height_76;
        __HELV_b_cur_top = __char_top_76;
        __HELV_b_cur_bottom = __char_bottom_76;
        break;
    case 77:
        rtnval = (uint8*) __char_77;
        __HELV_b_cur_wid = __char_wid_77;
        __HELV_b_cur_lstart = __char_lstart_77;
        __HELV_b_cur_height = __char_height_77;
        __HELV_b_cur_top = __char_top_77;
        __HELV_b_cur_bottom = __char_bottom_77;
        break;
    case 78:
        rtnval = (uint8*) __char_78;
        __HELV_b_cur_wid = __char_wid_78;
        __HELV_b_cur_lstart = __char_lstart_78;
        __HELV_b_cur_height = __char_height_78;
        __HELV_b_cur_top = __char_top_78;
        __HELV_b_cur_bottom = __char_bottom_78;
        break;
    case 79:
        rtnval = (uint8*) __char_79;
        __HELV_b_cur_wid = __char_wid_79;
        __HELV_b_cur_lstart = __char_lstart_79;
        __HELV_b_cur_height = __char_height_79;
        __HELV_b_cur_top = __char_top_79;
        __HELV_b_cur_bottom = __char_bottom_79;
        break;
    case 80:
        rtnval = (uint8*) __char_80;
        __HELV_b_cur_wid = __char_wid_80;
        __HELV_b_cur_lstart = __char_lstart_80;
        __HELV_b_cur_height = __char_height_80;
        __HELV_b_cur_top = __char_top_80;
        __HELV_b_cur_bottom = __char_bottom_80;
        break;
    case 81:
        rtnval = (uint8*) __char_81;
        __HELV_b_cur_wid = __char_wid_81;
        __HELV_b_cur_lstart = __char_lstart_81;
        __HELV_b_cur_height = __char_height_81;
        __HELV_b_cur_top = __char_top_81;
        __HELV_b_cur_bottom = __char_bottom_81;
        break;
    case 82:
        rtnval = (uint8*) __char_82;
        __HELV_b_cur_wid = __char_wid_82;
        __HELV_b_cur_lstart = __char_lstart_82;
        __HELV_b_cur_height = __char_height_82;
        __HELV_b_cur_top = __char_top_82;
        __HELV_b_cur_bottom = __char_bottom_82;
        break;
    case 83:
        rtnval = (uint8*) __char_83;
        __HELV_b_cur_wid = __char_wid_83;
        __HELV_b_cur_lstart = __char_lstart_83;
        __HELV_b_cur_height = __char_height_83;
        __HELV_b_cur_top = __char_top_83;
        __HELV_b_cur_bottom = __char_bottom_83;
        break;
    case 84:
        rtnval = (uint8*) __char_84;
        __HELV_b_cur_wid = __char_wid_84;
        __HELV_b_cur_lstart = __char_lstart_84;
        __HELV_b_cur_height = __char_height_84;
        __HELV_b_cur_top = __char_top_84;
        __HELV_b_cur_bottom = __char_bottom_84;
        break;
    case 85:
        rtnval = (uint8*) __char_85;
        __HELV_b_cur_wid = __char_wid_85;
        __HELV_b_cur_lstart = __char_lstart_85;
        __HELV_b_cur_height = __char_height_85;
        __HELV_b_cur_top = __char_top_85;
        __HELV_b_cur_bottom = __char_bottom_85;
        break;
    case 86:
        rtnval = (uint8*) __char_86;
        __HELV_b_cur_wid = __char_wid_86;
        __HELV_b_cur_lstart = __char_lstart_86;
        __HELV_b_cur_height = __char_height_86;
        __HELV_b_cur_top = __char_top_86;
        __HELV_b_cur_bottom = __char_bottom_86;
        break;
    case 87:
        rtnval = (uint8*) __char_87;
        __HELV_b_cur_wid = __char_wid_87;
        __HELV_b_cur_lstart = __char_lstart_87;
        __HELV_b_cur_height = __char_height_87;
        __HELV_b_cur_top = __char_top_87;
        __HELV_b_cur_bottom = __char_bottom_87;
        break;
    case 88:
        rtnval = (uint8*) __char_88;
        __HELV_b_cur_wid = __char_wid_88;
        __HELV_b_cur_lstart = __char_lstart_88;
        __HELV_b_cur_height = __char_height_88;
        __HELV_b_cur_top = __char_top_88;
        __HELV_b_cur_bottom = __char_bottom_88;
        break;
    case 89:
        rtnval = (uint8*) __char_89;
        __HELV_b_cur_wid = __char_wid_89;
        __HELV_b_cur_lstart = __char_lstart_89;
        __HELV_b_cur_height = __char_height_89;
        __HELV_b_cur_top = __char_top_89;
        __HELV_b_cur_bottom = __char_bottom_89;
        break;
    case 90:
        rtnval = (uint8*) __char_90;
        __HELV_b_cur_wid = __char_wid_90;
        __HELV_b_cur_lstart = __char_lstart_90;
        __HELV_b_cur_height = __char_height_90;
        __HELV_b_cur_top = __char_top_90;
        __HELV_b_cur_bottom = __char_bottom_90;
        break;
    case 91:
        rtnval = (uint8*) __char_91;
        __HELV_b_cur_wid = __char_wid_91;
        __HELV_b_cur_lstart = __char_lstart_91;
        __HELV_b_cur_height = __char_height_91;
        __HELV_b_cur_top = __char_top_91;
        __HELV_b_cur_bottom = __char_bottom_91;
        break;
    case 92:
        rtnval = (uint8*) __char_92;
        __HELV_b_cur_wid = __char_wid_92;
        __HELV_b_cur_lstart = __char_lstart_92;
        __HELV_b_cur_height = __char_height_92;
        __HELV_b_cur_top = __char_top_92;
        __HELV_b_cur_bottom = __char_bottom_92;
        break;
    case 93:
        rtnval = (uint8*) __char_93;
        __HELV_b_cur_wid = __char_wid_93;
        __HELV_b_cur_lstart = __char_lstart_93;
        __HELV_b_cur_height = __char_height_93;
        __HELV_b_cur_top = __char_top_93;
        __HELV_b_cur_bottom = __char_bottom_93;
        break;
    case 94:
        rtnval = (uint8*) __char_94;
        __HELV_b_cur_wid = __char_wid_94;
        __HELV_b_cur_lstart = __char_lstart_94;
        __HELV_b_cur_height = __char_height_94;
        __HELV_b_cur_top = __char_top_94;
        __HELV_b_cur_bottom = __char_bottom_94;
        break;
    case 95:
        rtnval = (uint8*) __char_95;
        __HELV_b_cur_wid = __char_wid_95;
        __HELV_b_cur_lstart = __char_lstart_95;
        __HELV_b_cur_height = __char_height_95;
        __HELV_b_cur_top = __char_top_95;
        __HELV_b_cur_bottom = __char_bottom_95;
        break;
    case 96:
        rtnval = (uint8*) __char_96;
        __HELV_b_cur_wid = __char_wid_96;
        __HELV_b_cur_lstart = __char_lstart_96;
        __HELV_b_cur_height = __char_height_96;
        __HELV_b_cur_top = __char_top_96;
        __HELV_b_cur_bottom = __char_bottom_96;
        break;
    case 97:
        rtnval = (uint8*) __char_97;
        __HELV_b_cur_wid = __char_wid_97;
        __HELV_b_cur_lstart = __char_lstart_97;
        __HELV_b_cur_height = __char_height_97;
        __HELV_b_cur_top = __char_top_97;
        __HELV_b_cur_bottom = __char_bottom_97;
        break;
    case 98:
        rtnval = (uint8*) __char_98;
        __HELV_b_cur_wid = __char_wid_98;
        __HELV_b_cur_lstart = __char_lstart_98;
        __HELV_b_cur_height = __char_height_98;
        __HELV_b_cur_top = __char_top_98;
        __HELV_b_cur_bottom = __char_bottom_98;
        break;
    case 99:
        rtnval = (uint8*) __char_99;
        __HELV_b_cur_wid = __char_wid_99;
        __HELV_b_cur_lstart = __char_lstart_99;
        __HELV_b_cur_height = __char_height_99;
        __HELV_b_cur_top = __char_top_99;
        __HELV_b_cur_bottom = __char_bottom_99;
        break;
    case 100:
        rtnval = (uint8*) __char_100;
        __HELV_b_cur_wid = __char_wid_100;
        __HELV_b_cur_lstart = __char_lstart_100;
        __HELV_b_cur_height = __char_height_100;
        __HELV_b_cur_top = __char_top_100;
        __HELV_b_cur_bottom = __char_bottom_100;
        break;
    case 101:
        rtnval = (uint8*) __char_101;
        __HELV_b_cur_wid = __char_wid_101;
        __HELV_b_cur_lstart = __char_lstart_101;
        __HELV_b_cur_height = __char_height_101;
        __HELV_b_cur_top = __char_top_101;
        __HELV_b_cur_bottom = __char_bottom_101;
        break;
    case 102:
        rtnval = (uint8*) __char_102;
        __HELV_b_cur_wid = __char_wid_102;
        __HELV_b_cur_lstart = __char_lstart_102;
        __HELV_b_cur_height = __char_height_102;
        __HELV_b_cur_top = __char_top_102;
        __HELV_b_cur_bottom = __char_bottom_102;
        break;
    case 103:
        rtnval = (uint8*) __char_103;
        __HELV_b_cur_wid = __char_wid_103;
        __HELV_b_cur_lstart = __char_lstart_103;
        __HELV_b_cur_height = __char_height_103;
        __HELV_b_cur_top = __char_top_103;
        __HELV_b_cur_bottom = __char_bottom_103;
        break;
    case 104:
        rtnval = (uint8*) __char_104;
        __HELV_b_cur_wid = __char_wid_104;
        __HELV_b_cur_lstart = __char_lstart_104;
        __HELV_b_cur_height = __char_height_104;
        __HELV_b_cur_top = __char_top_104;
        __HELV_b_cur_bottom = __char_bottom_104;
        break;
    case 105:
        rtnval = (uint8*) __char_105;
        __HELV_b_cur_wid = __char_wid_105;
        __HELV_b_cur_lstart = __char_lstart_105;
        __HELV_b_cur_height = __char_height_105;
        __HELV_b_cur_top = __char_top_105;
        __HELV_b_cur_bottom = __char_bottom_105;
        break;
    case 106:
        rtnval = (uint8*) __char_106;
        __HELV_b_cur_wid = __char_wid_106;
        __HELV_b_cur_lstart = __char_lstart_106;
        __HELV_b_cur_height = __char_height_106;
        __HELV_b_cur_top = __char_top_106;
        __HELV_b_cur_bottom = __char_bottom_106;
        break;
    case 107:
        rtnval = (uint8*) __char_107;
        __HELV_b_cur_wid = __char_wid_107;
        __HELV_b_cur_lstart = __char_lstart_107;
        __HELV_b_cur_height = __char_height_107;
        __HELV_b_cur_top = __char_top_107;
        __HELV_b_cur_bottom = __char_bottom_107;
        break;
    case 108:
        rtnval = (uint8*) __char_108;
        __HELV_b_cur_wid = __char_wid_108;
        __HELV_b_cur_lstart = __char_lstart_108;
        __HELV_b_cur_height = __char_height_108;
        __HELV_b_cur_top = __char_top_108;
        __HELV_b_cur_bottom = __char_bottom_108;
        break;
    case 109:
        rtnval = (uint8*) __char_109;
        __HELV_b_cur_wid = __char_wid_109;
        __HELV_b_cur_lstart = __char_lstart_109;
        __HELV_b_cur_height = __char_height_109;
        __HELV_b_cur_top = __char_top_109;
        __HELV_b_cur_bottom = __char_bottom_109;
        break;
    case 110:
        rtnval = (uint8*) __char_110;
        __HELV_b_cur_wid = __char_wid_110;
        __HELV_b_cur_lstart = __char_lstart_110;
        __HELV_b_cur_height = __char_height_110;
        __HELV_b_cur_top = __char_top_110;
        __HELV_b_cur_bottom = __char_bottom_110;
        break;
    case 111:
        rtnval = (uint8*) __char_111;
        __HELV_b_cur_wid = __char_wid_111;
        __HELV_b_cur_lstart = __char_lstart_111;
        __HELV_b_cur_height = __char_height_111;
        __HELV_b_cur_top = __char_top_111;
        __HELV_b_cur_bottom = __char_bottom_111;
        break;
    case 112:
        rtnval = (uint8*) __char_112;
        __HELV_b_cur_wid = __char_wid_112;
        __HELV_b_cur_lstart = __char_lstart_112;
        __HELV_b_cur_height = __char_height_112;
        __HELV_b_cur_top = __char_top_112;
        __HELV_b_cur_bottom = __char_bottom_112;
        break;
    case 113:
        rtnval = (uint8*) __char_113;
        __HELV_b_cur_wid = __char_wid_113;
        __HELV_b_cur_lstart = __char_lstart_113;
        __HELV_b_cur_height = __char_height_113;
        __HELV_b_cur_top = __char_top_113;
        __HELV_b_cur_bottom = __char_bottom_113;
        break;
    case 114:
        rtnval = (uint8*) __char_114;
        __HELV_b_cur_wid = __char_wid_114;
        __HELV_b_cur_lstart = __char_lstart_114;
        __HELV_b_cur_height = __char_height_114;
        __HELV_b_cur_top = __char_top_114;
        __HELV_b_cur_bottom = __char_bottom_114;
        break;
    case 115:
        rtnval = (uint8*) __char_115;
        __HELV_b_cur_wid = __char_wid_115;
        __HELV_b_cur_lstart = __char_lstart_115;
        __HELV_b_cur_height = __char_height_115;
        __HELV_b_cur_top = __char_top_115;
        __HELV_b_cur_bottom = __char_bottom_115;
        break;
    case 116:
        rtnval = (uint8*) __char_116;
        __HELV_b_cur_wid = __char_wid_116;
        __HELV_b_cur_lstart = __char_lstart_116;
        __HELV_b_cur_height = __char_height_116;
        __HELV_b_cur_top = __char_top_116;
        __HELV_b_cur_bottom = __char_bottom_116;
        break;
    case 117:
        rtnval = (uint8*) __char_117;
        __HELV_b_cur_wid = __char_wid_117;
        __HELV_b_cur_lstart = __char_lstart_117;
        __HELV_b_cur_height = __char_height_117;
        __HELV_b_cur_top = __char_top_117;
        __HELV_b_cur_bottom = __char_bottom_117;
        break;
    case 118:
        rtnval = (uint8*) __char_118;
        __HELV_b_cur_wid = __char_wid_118;
        __HELV_b_cur_lstart = __char_lstart_118;
        __HELV_b_cur_height = __char_height_118;
        __HELV_b_cur_top = __char_top_118;
        __HELV_b_cur_bottom = __char_bottom_118;
        break;
    case 119:
        rtnval = (uint8*) __char_119;
        __HELV_b_cur_wid = __char_wid_119;
        __HELV_b_cur_lstart = __char_lstart_119;
        __HELV_b_cur_height = __char_height_119;
        __HELV_b_cur_top = __char_top_119;
        __HELV_b_cur_bottom = __char_bottom_119;
        break;
    case 120:
        rtnval = (uint8*) __char_120;
        __HELV_b_cur_wid = __char_wid_120;
        __HELV_b_cur_lstart = __char_lstart_120;
        __HELV_b_cur_height = __char_height_120;
        __HELV_b_cur_top = __char_top_120;
        __HELV_b_cur_bottom = __char_bottom_120;
        break;
    case 121:
        rtnval = (uint8*) __char_121;
        __HELV_b_cur_wid = __char_wid_121;
        __HELV_b_cur_lstart = __char_lstart_121;
        __HELV_b_cur_height = __char_height_121;
        __HELV_b_cur_top = __char_top_121;
        __HELV_b_cur_bottom = __char_bottom_121;
        break;
    case 122:
        rtnval = (uint8*) __char_122;
        __HELV_b_cur_wid = __char_wid_122;
        __HELV_b_cur_lstart = __char_lstart_122;
        __HELV_b_cur_height = __char_height_122;
        __HELV_b_cur_top = __char_top_122;
        __HELV_b_cur_bottom = __char_bottom_122;
        break;
    case 123:
        rtnval = (uint8*) __char_123;
        __HELV_b_cur_wid = __char_wid_123;
        __HELV_b_cur_lstart = __char_lstart_123;
        __HELV_b_cur_height = __char_height_123;
        __HELV_b_cur_top = __char_top_123;
        __HELV_b_cur_bottom = __char_bottom_123;
        break;
    case 124:
        rtnval = (uint8*) __char_124;
        __HELV_b_cur_wid = __char_wid_124;
        __HELV_b_cur_lstart = __char_lstart_124;
        __HELV_b_cur_height = __char_height_124;
        __HELV_b_cur_top = __char_top_124;
        __HELV_b_cur_bottom = __char_bottom_124;
        break;
    case 125:
        rtnval = (uint8*) __char_125;
        __HELV_b_cur_wid = __char_wid_125;
        __HELV_b_cur_lstart = __char_lstart_125;
        __HELV_b_cur_height = __char_height_125;
        __HELV_b_cur_top = __char_top_125;
        __HELV_b_cur_bottom = __char_bottom_125;
        break;
    case 126:
        rtnval = (uint8*) __char_126;
        __HELV_b_cur_wid = __char_wid_126;
        __HELV_b_cur_lstart = __char_lstart_126;
        __HELV_b_cur_height = __char_height_126;
        __HELV_b_cur_top = __char_top_126;
        __HELV_b_cur_bottom = __char_bottom_126;
        break;
    case 127:
        rtnval = (uint8*) __char_127;
        __HELV_b_cur_wid = __char_wid_127;
        __HELV_b_cur_lstart = __char_lstart_127;
        __HELV_b_cur_height = __char_height_127;
        __HELV_b_cur_top = __char_top_127;
        __HELV_b_cur_bottom = __char_bottom_127;
        break;
    case 128:
        rtnval = (uint8*) __char_128;
        __HELV_b_cur_wid = __char_wid_128;
        __HELV_b_cur_lstart = __char_lstart_128;
        __HELV_b_cur_height = __char_height_128;
        __HELV_b_cur_top = __char_top_128;
        __HELV_b_cur_bottom = __char_bottom_128;
        break;
    case 129:
        rtnval = (uint8*) __char_129;
        __HELV_b_cur_wid = __char_wid_129;
        __HELV_b_cur_lstart = __char_lstart_129;
        __HELV_b_cur_height = __char_height_129;
        __HELV_b_cur_top = __char_top_129;
        __HELV_b_cur_bottom = __char_bottom_129;
        break;
    case 130:
        rtnval = (uint8*) __char_130;
        __HELV_b_cur_wid = __char_wid_130;
        __HELV_b_cur_lstart = __char_lstart_130;
        __HELV_b_cur_height = __char_height_130;
        __HELV_b_cur_top = __char_top_130;
        __HELV_b_cur_bottom = __char_bottom_130;
        break;
    case 131:
        rtnval = (uint8*) __char_131;
        __HELV_b_cur_wid = __char_wid_131;
        __HELV_b_cur_lstart = __char_lstart_131;
        __HELV_b_cur_height = __char_height_131;
        __HELV_b_cur_top = __char_top_131;
        __HELV_b_cur_bottom = __char_bottom_131;
        break;
    case 132:
        rtnval = (uint8*) __char_132;
        __HELV_b_cur_wid = __char_wid_132;
        __HELV_b_cur_lstart = __char_lstart_132;
        __HELV_b_cur_height = __char_height_132;
        __HELV_b_cur_top = __char_top_132;
        __HELV_b_cur_bottom = __char_bottom_132;
        break;
    case 133:
        rtnval = (uint8*) __char_133;
        __HELV_b_cur_wid = __char_wid_133;
        __HELV_b_cur_lstart = __char_lstart_133;
        __HELV_b_cur_height = __char_height_133;
        __HELV_b_cur_top = __char_top_133;
        __HELV_b_cur_bottom = __char_bottom_133;
        break;
    case 134:
        rtnval = (uint8*) __char_134;
        __HELV_b_cur_wid = __char_wid_134;
        __HELV_b_cur_lstart = __char_lstart_134;
        __HELV_b_cur_height = __char_height_134;
        __HELV_b_cur_top = __char_top_134;
        __HELV_b_cur_bottom = __char_bottom_134;
        break;
    case 135:
        rtnval = (uint8*) __char_135;
        __HELV_b_cur_wid = __char_wid_135;
        __HELV_b_cur_lstart = __char_lstart_135;
        __HELV_b_cur_height = __char_height_135;
        __HELV_b_cur_top = __char_top_135;
        __HELV_b_cur_bottom = __char_bottom_135;
        break;
    case 136:
        rtnval = (uint8*) __char_136;
        __HELV_b_cur_wid = __char_wid_136;
        __HELV_b_cur_lstart = __char_lstart_136;
        __HELV_b_cur_height = __char_height_136;
        __HELV_b_cur_top = __char_top_136;
        __HELV_b_cur_bottom = __char_bottom_136;
        break;
    case 137:
        rtnval = (uint8*) __char_137;
        __HELV_b_cur_wid = __char_wid_137;
        __HELV_b_cur_lstart = __char_lstart_137;
        __HELV_b_cur_height = __char_height_137;
        __HELV_b_cur_top = __char_top_137;
        __HELV_b_cur_bottom = __char_bottom_137;
        break;
    case 138:
        rtnval = (uint8*) __char_138;
        __HELV_b_cur_wid = __char_wid_138;
        __HELV_b_cur_lstart = __char_lstart_138;
        __HELV_b_cur_height = __char_height_138;
        __HELV_b_cur_top = __char_top_138;
        __HELV_b_cur_bottom = __char_bottom_138;
        break;
    case 139:
        rtnval = (uint8*) __char_139;
        __HELV_b_cur_wid = __char_wid_139;
        __HELV_b_cur_lstart = __char_lstart_139;
        __HELV_b_cur_height = __char_height_139;
        __HELV_b_cur_top = __char_top_139;
        __HELV_b_cur_bottom = __char_bottom_139;
        break;
    case 140:
        rtnval = (uint8*) __char_140;
        __HELV_b_cur_wid = __char_wid_140;
        __HELV_b_cur_lstart = __char_lstart_140;
        __HELV_b_cur_height = __char_height_140;
        __HELV_b_cur_top = __char_top_140;
        __HELV_b_cur_bottom = __char_bottom_140;
        break;
    case 141:
        rtnval = (uint8*) __char_141;
        __HELV_b_cur_wid = __char_wid_141;
        __HELV_b_cur_lstart = __char_lstart_141;
        __HELV_b_cur_height = __char_height_141;
        __HELV_b_cur_top = __char_top_141;
        __HELV_b_cur_bottom = __char_bottom_141;
        break;
    case 142:
        rtnval = (uint8*) __char_142;
        __HELV_b_cur_wid = __char_wid_142;
        __HELV_b_cur_lstart = __char_lstart_142;
        __HELV_b_cur_height = __char_height_142;
        __HELV_b_cur_top = __char_top_142;
        __HELV_b_cur_bottom = __char_bottom_142;
        break;
    case 143:
        rtnval = (uint8*) __char_143;
        __HELV_b_cur_wid = __char_wid_143;
        __HELV_b_cur_lstart = __char_lstart_143;
        __HELV_b_cur_height = __char_height_143;
        __HELV_b_cur_top = __char_top_143;
        __HELV_b_cur_bottom = __char_bottom_143;
        break;
    case 144:
        rtnval = (uint8*) __char_144;
        __HELV_b_cur_wid = __char_wid_144;
        __HELV_b_cur_lstart = __char_lstart_144;
        __HELV_b_cur_height = __char_height_144;
        __HELV_b_cur_top = __char_top_144;
        __HELV_b_cur_bottom = __char_bottom_144;
        break;
    case 145:
        rtnval = (uint8*) __char_145;
        __HELV_b_cur_wid = __char_wid_145;
        __HELV_b_cur_lstart = __char_lstart_145;
        __HELV_b_cur_height = __char_height_145;
        __HELV_b_cur_top = __char_top_145;
        __HELV_b_cur_bottom = __char_bottom_145;
        break;
    case 146:
        rtnval = (uint8*) __char_146;
        __HELV_b_cur_wid = __char_wid_146;
        __HELV_b_cur_lstart = __char_lstart_146;
        __HELV_b_cur_height = __char_height_146;
        __HELV_b_cur_top = __char_top_146;
        __HELV_b_cur_bottom = __char_bottom_146;
        break;
    case 147:
        rtnval = (uint8*) __char_147;
        __HELV_b_cur_wid = __char_wid_147;
        __HELV_b_cur_lstart = __char_lstart_147;
        __HELV_b_cur_height = __char_height_147;
        __HELV_b_cur_top = __char_top_147;
        __HELV_b_cur_bottom = __char_bottom_147;
        break;
    case 148:
        rtnval = (uint8*) __char_148;
        __HELV_b_cur_wid = __char_wid_148;
        __HELV_b_cur_lstart = __char_lstart_148;
        __HELV_b_cur_height = __char_height_148;
        __HELV_b_cur_top = __char_top_148;
        __HELV_b_cur_bottom = __char_bottom_148;
        break;
    case 149:
        rtnval = (uint8*) __char_149;
        __HELV_b_cur_wid = __char_wid_149;
        __HELV_b_cur_lstart = __char_lstart_149;
        __HELV_b_cur_height = __char_height_149;
        __HELV_b_cur_top = __char_top_149;
        __HELV_b_cur_bottom = __char_bottom_149;
        break;
    case 150:
        rtnval = (uint8*) __char_150;
        __HELV_b_cur_wid = __char_wid_150;
        __HELV_b_cur_lstart = __char_lstart_150;
        __HELV_b_cur_height = __char_height_150;
        __HELV_b_cur_top = __char_top_150;
        __HELV_b_cur_bottom = __char_bottom_150;
        break;
    case 151:
        rtnval = (uint8*) __char_151;
        __HELV_b_cur_wid = __char_wid_151;
        __HELV_b_cur_lstart = __char_lstart_151;
        __HELV_b_cur_height = __char_height_151;
        __HELV_b_cur_top = __char_top_151;
        __HELV_b_cur_bottom = __char_bottom_151;
        break;
    case 152:
        rtnval = (uint8*) __char_152;
        __HELV_b_cur_wid = __char_wid_152;
        __HELV_b_cur_lstart = __char_lstart_152;
        __HELV_b_cur_height = __char_height_152;
        __HELV_b_cur_top = __char_top_152;
        __HELV_b_cur_bottom = __char_bottom_152;
        break;
    case 153:
        rtnval = (uint8*) __char_153;
        __HELV_b_cur_wid = __char_wid_153;
        __HELV_b_cur_lstart = __char_lstart_153;
        __HELV_b_cur_height = __char_height_153;
        __HELV_b_cur_top = __char_top_153;
        __HELV_b_cur_bottom = __char_bottom_153;
        break;
    case 154:
        rtnval = (uint8*) __char_154;
        __HELV_b_cur_wid = __char_wid_154;
        __HELV_b_cur_lstart = __char_lstart_154;
        __HELV_b_cur_height = __char_height_154;
        __HELV_b_cur_top = __char_top_154;
        __HELV_b_cur_bottom = __char_bottom_154;
        break;
    case 155:
        rtnval = (uint8*) __char_155;
        __HELV_b_cur_wid = __char_wid_155;
        __HELV_b_cur_lstart = __char_lstart_155;
        __HELV_b_cur_height = __char_height_155;
        __HELV_b_cur_top = __char_top_155;
        __HELV_b_cur_bottom = __char_bottom_155;
        break;
    case 156:
        rtnval = (uint8*) __char_156;
        __HELV_b_cur_wid = __char_wid_156;
        __HELV_b_cur_lstart = __char_lstart_156;
        __HELV_b_cur_height = __char_height_156;
        __HELV_b_cur_top = __char_top_156;
        __HELV_b_cur_bottom = __char_bottom_156;
        break;
    case 157:
        rtnval = (uint8*) __char_157;
        __HELV_b_cur_wid = __char_wid_157;
        __HELV_b_cur_lstart = __char_lstart_157;
        __HELV_b_cur_height = __char_height_157;
        __HELV_b_cur_top = __char_top_157;
        __HELV_b_cur_bottom = __char_bottom_157;
        break;
    case 158:
        rtnval = (uint8*) __char_158;
        __HELV_b_cur_wid = __char_wid_158;
        __HELV_b_cur_lstart = __char_lstart_158;
        __HELV_b_cur_height = __char_height_158;
        __HELV_b_cur_top = __char_top_158;
        __HELV_b_cur_bottom = __char_bottom_158;
        break;
    case 159:
        rtnval = (uint8*) __char_159;
        __HELV_b_cur_wid = __char_wid_159;
        __HELV_b_cur_lstart = __char_lstart_159;
        __HELV_b_cur_height = __char_height_159;
        __HELV_b_cur_top = __char_top_159;
        __HELV_b_cur_bottom = __char_bottom_159;
        break;
    case 160:
        rtnval = (uint8*) __char_160;
        __HELV_b_cur_wid = __char_wid_160;
        __HELV_b_cur_lstart = __char_lstart_160;
        __HELV_b_cur_height = __char_height_160;
        __HELV_b_cur_top = __char_top_160;
        __HELV_b_cur_bottom = __char_bottom_160;
        break;
    case 161:
        rtnval = (uint8*) __char_161;
        __HELV_b_cur_wid = __char_wid_161;
        __HELV_b_cur_lstart = __char_lstart_161;
        __HELV_b_cur_height = __char_height_161;
        __HELV_b_cur_top = __char_top_161;
        __HELV_b_cur_bottom = __char_bottom_161;
        break;
    case 162:
        rtnval = (uint8*) __char_162;
        __HELV_b_cur_wid = __char_wid_162;
        __HELV_b_cur_lstart = __char_lstart_162;
        __HELV_b_cur_height = __char_height_162;
        __HELV_b_cur_top = __char_top_162;
        __HELV_b_cur_bottom = __char_bottom_162;
        break;
    case 163:
        rtnval = (uint8*) __char_163;
        __HELV_b_cur_wid = __char_wid_163;
        __HELV_b_cur_lstart = __char_lstart_163;
        __HELV_b_cur_height = __char_height_163;
        __HELV_b_cur_top = __char_top_163;
        __HELV_b_cur_bottom = __char_bottom_163;
        break;
    case 164:
        rtnval = (uint8*) __char_164;
        __HELV_b_cur_wid = __char_wid_164;
        __HELV_b_cur_lstart = __char_lstart_164;
        __HELV_b_cur_height = __char_height_164;
        __HELV_b_cur_top = __char_top_164;
        __HELV_b_cur_bottom = __char_bottom_164;
        break;
    case 165:
        rtnval = (uint8*) __char_165;
        __HELV_b_cur_wid = __char_wid_165;
        __HELV_b_cur_lstart = __char_lstart_165;
        __HELV_b_cur_height = __char_height_165;
        __HELV_b_cur_top = __char_top_165;
        __HELV_b_cur_bottom = __char_bottom_165;
        break;
    case 166:
        rtnval = (uint8*) __char_166;
        __HELV_b_cur_wid = __char_wid_166;
        __HELV_b_cur_lstart = __char_lstart_166;
        __HELV_b_cur_height = __char_height_166;
        __HELV_b_cur_top = __char_top_166;
        __HELV_b_cur_bottom = __char_bottom_166;
        break;
    case 167:
        rtnval = (uint8*) __char_167;
        __HELV_b_cur_wid = __char_wid_167;
        __HELV_b_cur_lstart = __char_lstart_167;
        __HELV_b_cur_height = __char_height_167;
        __HELV_b_cur_top = __char_top_167;
        __HELV_b_cur_bottom = __char_bottom_167;
        break;
    case 168:
        rtnval = (uint8*) __char_168;
        __HELV_b_cur_wid = __char_wid_168;
        __HELV_b_cur_lstart = __char_lstart_168;
        __HELV_b_cur_height = __char_height_168;
        __HELV_b_cur_top = __char_top_168;
        __HELV_b_cur_bottom = __char_bottom_168;
        break;
    case 169:
        rtnval = (uint8*) __char_169;
        __HELV_b_cur_wid = __char_wid_169;
        __HELV_b_cur_lstart = __char_lstart_169;
        __HELV_b_cur_height = __char_height_169;
        __HELV_b_cur_top = __char_top_169;
        __HELV_b_cur_bottom = __char_bottom_169;
        break;
    case 170:
        rtnval = (uint8*) __char_170;
        __HELV_b_cur_wid = __char_wid_170;
        __HELV_b_cur_lstart = __char_lstart_170;
        __HELV_b_cur_height = __char_height_170;
        __HELV_b_cur_top = __char_top_170;
        __HELV_b_cur_bottom = __char_bottom_170;
        break;
    case 171:
        rtnval = (uint8*) __char_171;
        __HELV_b_cur_wid = __char_wid_171;
        __HELV_b_cur_lstart = __char_lstart_171;
        __HELV_b_cur_height = __char_height_171;
        __HELV_b_cur_top = __char_top_171;
        __HELV_b_cur_bottom = __char_bottom_171;
        break;
    case 172:
        rtnval = (uint8*) __char_172;
        __HELV_b_cur_wid = __char_wid_172;
        __HELV_b_cur_lstart = __char_lstart_172;
        __HELV_b_cur_height = __char_height_172;
        __HELV_b_cur_top = __char_top_172;
        __HELV_b_cur_bottom = __char_bottom_172;
        break;
    case 173:
        rtnval = (uint8*) __char_173;
        __HELV_b_cur_wid = __char_wid_173;
        __HELV_b_cur_lstart = __char_lstart_173;
        __HELV_b_cur_height = __char_height_173;
        __HELV_b_cur_top = __char_top_173;
        __HELV_b_cur_bottom = __char_bottom_173;
        break;
    case 174:
        rtnval = (uint8*) __char_174;
        __HELV_b_cur_wid = __char_wid_174;
        __HELV_b_cur_lstart = __char_lstart_174;
        __HELV_b_cur_height = __char_height_174;
        __HELV_b_cur_top = __char_top_174;
        __HELV_b_cur_bottom = __char_bottom_174;
        break;
    case 175:
        rtnval = (uint8*) __char_175;
        __HELV_b_cur_wid = __char_wid_175;
        __HELV_b_cur_lstart = __char_lstart_175;
        __HELV_b_cur_height = __char_height_175;
        __HELV_b_cur_top = __char_top_175;
        __HELV_b_cur_bottom = __char_bottom_175;
        break;
    case 176:
        rtnval = (uint8*) __char_176;
        __HELV_b_cur_wid = __char_wid_176;
        __HELV_b_cur_lstart = __char_lstart_176;
        __HELV_b_cur_height = __char_height_176;
        __HELV_b_cur_top = __char_top_176;
        __HELV_b_cur_bottom = __char_bottom_176;
        break;
    default: /* Character not printable */
break;
    }
    return rtnval;
}


int get_char_graphic_width(char char_to_place){
    int rtnval = 0;
    switch(char_to_place){
    case 33:
        rtnval = __char_wid_33;
        break;
    case 34:
        rtnval = __char_wid_34;
        break;
    case 35:
        rtnval = __char_wid_35;
        break;
    case 36:
        rtnval = __char_wid_36;
        break;
    case 37:
        rtnval = __char_wid_37;
        break;
    case 38:
        rtnval = __char_wid_38;
        break;
    case 39:
        rtnval = __char_wid_39;
        break;
    case 40:
        rtnval = __char_wid_40;
        break;
    case 41:
        rtnval = __char_wid_41;
        break;
    case 42:
        rtnval = __char_wid_42;
        break;
    case 43:
        rtnval = __char_wid_43;
        break;
    case 44:
        rtnval = __char_wid_44;
        break;
    case 45:
        rtnval = __char_wid_45;
        break;
    case 46:
        rtnval = __char_wid_46;
        break;
    case 47:
        rtnval = __char_wid_47;
        break;
    case 48:
        rtnval = __char_wid_48;
        break;
    case 49:
        rtnval = __char_wid_49;
        break;
    case 50:
        rtnval = __char_wid_50;
        break;
    case 51:
        rtnval = __char_wid_51;
        break;
    case 52:
        rtnval = __char_wid_52;
        break;
    case 53:
        rtnval = __char_wid_53;
        break;
    case 54:
        rtnval = __char_wid_54;
        break;
    case 55:
        rtnval = __char_wid_55;
        break;
    case 56:
        rtnval = __char_wid_56;
        break;
    case 57:
        rtnval = __char_wid_57;
        break;
    case 58:
        rtnval = __char_wid_58;
        break;
    case 59:
        rtnval = __char_wid_59;
        break;
    case 60:
        rtnval = __char_wid_60;
        break;
    case 61:
        rtnval = __char_wid_61;
        break;
    case 62:
        rtnval = __char_wid_62;
        break;
    case 63:
        rtnval = __char_wid_63;
        break;
    case 64:
        rtnval = __char_wid_64;
        break;
    case 65:
        rtnval = __char_wid_65;
        break;
    case 66:
        rtnval = __char_wid_66;
        break;
    case 67:
        rtnval = __char_wid_67;
        break;
    case 68:
        rtnval = __char_wid_68;
        break;
    case 69:
        rtnval = __char_wid_69;
        break;
    case 70:
        rtnval = __char_wid_70;
        break;
    case 71:
        rtnval = __char_wid_71;
        break;
    case 72:
        rtnval = __char_wid_72;
        break;
    case 73:
        rtnval = __char_wid_73;
        break;
    case 74:
        rtnval = __char_wid_74;
        break;
    case 75:
        rtnval = __char_wid_75;
        break;
    case 76:
        rtnval = __char_wid_76;
        break;
    case 77:
        rtnval = __char_wid_77;
        break;
    case 78:
        rtnval = __char_wid_78;
        break;
    case 79:
        rtnval = __char_wid_79;
        break;
    case 80:
        rtnval = __char_wid_80;
        break;
    case 81:
        rtnval = __char_wid_81;
        break;
    case 82:
        rtnval = __char_wid_82;
        break;
    case 83:
        rtnval = __char_wid_83;
        break;
    case 84:
        rtnval = __char_wid_84;
        break;
    case 85:
        rtnval = __char_wid_85;
        break;
    case 86:
        rtnval = __char_wid_86;
        break;
    case 87:
        rtnval = __char_wid_87;
        break;
    case 88:
        rtnval = __char_wid_88;
        break;
    case 89:
        rtnval = __char_wid_89;
        break;
    case 90:
        rtnval = __char_wid_90;
        break;
    case 91:
        rtnval = __char_wid_91;
        break;
    case 92:
        rtnval = __char_wid_92;
        break;
    case 93:
        rtnval = __char_wid_93;
        break;
    case 94:
        rtnval = __char_wid_94;
        break;
    case 95:
        rtnval = __char_wid_95;
        break;
    case 96:
        rtnval = __char_wid_96;
        break;
    case 97:
        rtnval = __char_wid_97;
        break;
    case 98:
        rtnval = __char_wid_98;
        break;
    case 99:
        rtnval = __char_wid_99;
        break;
    case 100:
        rtnval = __char_wid_100;
        break;
    case 101:
        rtnval = __char_wid_101;
        break;
    case 102:
        rtnval = __char_wid_102;
        break;
    case 103:
        rtnval = __char_wid_103;
        break;
    case 104:
        rtnval = __char_wid_104;
        break;
    case 105:
        rtnval = __char_wid_105;
        break;
    case 106:
        rtnval = __char_wid_106;
        break;
    case 107:
        rtnval = __char_wid_107;
        break;
    case 108:
        rtnval = __char_wid_108;
        break;
    case 109:
        rtnval = __char_wid_109;
        break;
    case 110:
        rtnval = __char_wid_110;
        break;
    case 111:
        rtnval = __char_wid_111;
        break;
    case 112:
        rtnval = __char_wid_112;
        break;
    case 113:
        rtnval = __char_wid_113;
        break;
    case 114:
        rtnval = __char_wid_114;
        break;
    case 115:
        rtnval = __char_wid_115;
        break;
    case 116:
        rtnval = __char_wid_116;
        break;
    case 117:
        rtnval = __char_wid_117;
        break;
    case 118:
        rtnval = __char_wid_118;
        break;
    case 119:
        rtnval = __char_wid_119;
        break;
    case 120:
        rtnval = __char_wid_120;
        break;
    case 121:
        rtnval = __char_wid_121;
        break;
    case 122:
        rtnval = __char_wid_122;
        break;
    case 123:
        rtnval = __char_wid_123;
        break;
    case 124:
        rtnval = __char_wid_124;
        break;
    case 125:
        rtnval = __char_wid_125;
        break;
    case 126:
        rtnval = __char_wid_126;
        break;
    case 127:
        rtnval = __char_wid_127;
        break;
    case 128:
        rtnval = __char_wid_128;
        break;
    case 129:
        rtnval = __char_wid_129;
        break;
    case 130:
        rtnval = __char_wid_130;
        break;
    case 131:
        rtnval = __char_wid_131;
        break;
    case 132:
        rtnval = __char_wid_132;
        break;
    case 133:
        rtnval = __char_wid_133;
        break;
    case 134:
        rtnval = __char_wid_134;
        break;
    case 135:
        rtnval = __char_wid_135;
        break;
    case 136:
        rtnval = __char_wid_136;
        break;
    case 137:
        rtnval = __char_wid_137;
        break;
    case 138:
        rtnval = __char_wid_138;
        break;
    case 139:
        rtnval = __char_wid_139;
        break;
    case 140:
        rtnval = __char_wid_140;
        break;
    case 141:
        rtnval = __char_wid_141;
        break;
    case 142:
        rtnval = __char_wid_142;
        break;
    case 143:
        rtnval = __char_wid_143;
        break;
    case 144:
        rtnval = __char_wid_144;
        break;
    case 145:
        rtnval = __char_wid_145;
        break;
    case 146:
        rtnval = __char_wid_146;
        break;
    case 147:
        rtnval = __char_wid_147;
        break;
    case 148:
        rtnval = __char_wid_148;
        break;
    case 149:
        rtnval = __char_wid_149;
        break;
    case 150:
        rtnval = __char_wid_150;
        break;
    case 151:
        rtnval = __char_wid_151;
        break;
    case 152:
        rtnval = __char_wid_152;
        break;
    case 153:
        rtnval = __char_wid_153;
        break;
    case 154:
        rtnval = __char_wid_154;
        break;
    case 155:
        rtnval = __char_wid_155;
        break;
    case 156:
        rtnval = __char_wid_156;
        break;
    case 157:
        rtnval = __char_wid_157;
        break;
    case 158:
        rtnval = __char_wid_158;
        break;
    case 159:
        rtnval = __char_wid_159;
        break;
    case 160:
        rtnval = __char_wid_160;
        break;
    case 161:
        rtnval = __char_wid_161;
        break;
    case 162:
        rtnval = __char_wid_162;
        break;
    case 163:
        rtnval = __char_wid_163;
        break;
    case 164:
        rtnval = __char_wid_164;
        break;
    case 165:
        rtnval = __char_wid_165;
        break;
    case 166:
        rtnval = __char_wid_166;
        break;
    case 167:
        rtnval = __char_wid_167;
        break;
    case 168:
        rtnval = __char_wid_168;
        break;
    case 169:
        rtnval = __char_wid_169;
        break;
    case 170:
        rtnval = __char_wid_170;
        break;
    case 171:
        rtnval = __char_wid_171;
        break;
    case 172:
        rtnval = __char_wid_172;
        break;
    case 173:
        rtnval = __char_wid_173;
        break;
    case 174:
        rtnval = __char_wid_174;
        break;
    case 175:
        rtnval = __char_wid_175;
        break;
    case 176:
        rtnval = __char_wid_176;
        break;
    default: /* Character not printable */
break;
    }
    return rtnval;
}


int get_char_graphic_lstart(char char_to_place){
    int rtnval = 0;
    switch(char_to_place){
    case 33:
        rtnval = __char_lstart_33;
        break;
    case 34:
        rtnval = __char_lstart_34;
        break;
    case 35:
        rtnval = __char_lstart_35;
        break;
    case 36:
        rtnval = __char_lstart_36;
        break;
    case 37:
        rtnval = __char_lstart_37;
        break;
    case 38:
        rtnval = __char_lstart_38;
        break;
    case 39:
        rtnval = __char_lstart_39;
        break;
    case 40:
        rtnval = __char_lstart_40;
        break;
    case 41:
        rtnval = __char_lstart_41;
        break;
    case 42:
        rtnval = __char_lstart_42;
        break;
    case 43:
        rtnval = __char_lstart_43;
        break;
    case 44:
        rtnval = __char_lstart_44;
        break;
    case 45:
        rtnval = __char_lstart_45;
        break;
    case 46:
        rtnval = __char_lstart_46;
        break;
    case 47:
        rtnval = __char_lstart_47;
        break;
    case 48:
        rtnval = __char_lstart_48;
        break;
    case 49:
        rtnval = __char_lstart_49;
        break;
    case 50:
        rtnval = __char_lstart_50;
        break;
    case 51:
        rtnval = __char_lstart_51;
        break;
    case 52:
        rtnval = __char_lstart_52;
        break;
    case 53:
        rtnval = __char_lstart_53;
        break;
    case 54:
        rtnval = __char_lstart_54;
        break;
    case 55:
        rtnval = __char_lstart_55;
        break;
    case 56:
        rtnval = __char_lstart_56;
        break;
    case 57:
        rtnval = __char_lstart_57;
        break;
    case 58:
        rtnval = __char_lstart_58;
        break;
    case 59:
        rtnval = __char_lstart_59;
        break;
    case 60:
        rtnval = __char_lstart_60;
        break;
    case 61:
        rtnval = __char_lstart_61;
        break;
    case 62:
        rtnval = __char_lstart_62;
        break;
    case 63:
        rtnval = __char_lstart_63;
        break;
    case 64:
        rtnval = __char_lstart_64;
        break;
    case 65:
        rtnval = __char_lstart_65;
        break;
    case 66:
        rtnval = __char_lstart_66;
        break;
    case 67:
        rtnval = __char_lstart_67;
        break;
    case 68:
        rtnval = __char_lstart_68;
        break;
    case 69:
        rtnval = __char_lstart_69;
        break;
    case 70:
        rtnval = __char_lstart_70;
        break;
    case 71:
        rtnval = __char_lstart_71;
        break;
    case 72:
        rtnval = __char_lstart_72;
        break;
    case 73:
        rtnval = __char_lstart_73;
        break;
    case 74:
        rtnval = __char_lstart_74;
        break;
    case 75:
        rtnval = __char_lstart_75;
        break;
    case 76:
        rtnval = __char_lstart_76;
        break;
    case 77:
        rtnval = __char_lstart_77;
        break;
    case 78:
        rtnval = __char_lstart_78;
        break;
    case 79:
        rtnval = __char_lstart_79;
        break;
    case 80:
        rtnval = __char_lstart_80;
        break;
    case 81:
        rtnval = __char_lstart_81;
        break;
    case 82:
        rtnval = __char_lstart_82;
        break;
    case 83:
        rtnval = __char_lstart_83;
        break;
    case 84:
        rtnval = __char_lstart_84;
        break;
    case 85:
        rtnval = __char_lstart_85;
        break;
    case 86:
        rtnval = __char_lstart_86;
        break;
    case 87:
        rtnval = __char_lstart_87;
        break;
    case 88:
        rtnval = __char_lstart_88;
        break;
    case 89:
        rtnval = __char_lstart_89;
        break;
    case 90:
        rtnval = __char_lstart_90;
        break;
    case 91:
        rtnval = __char_lstart_91;
        break;
    case 92:
        rtnval = __char_lstart_92;
        break;
    case 93:
        rtnval = __char_lstart_93;
        break;
    case 94:
        rtnval = __char_lstart_94;
        break;
    case 95:
        rtnval = __char_lstart_95;
        break;
    case 96:
        rtnval = __char_lstart_96;
        break;
    case 97:
        rtnval = __char_lstart_97;
        break;
    case 98:
        rtnval = __char_lstart_98;
        break;
    case 99:
        rtnval = __char_lstart_99;
        break;
    case 100:
        rtnval = __char_lstart_100;
        break;
    case 101:
        rtnval = __char_lstart_101;
        break;
    case 102:
        rtnval = __char_lstart_102;
        break;
    case 103:
        rtnval = __char_lstart_103;
        break;
    case 104:
        rtnval = __char_lstart_104;
        break;
    case 105:
        rtnval = __char_lstart_105;
        break;
    case 106:
        rtnval = __char_lstart_106;
        break;
    case 107:
        rtnval = __char_lstart_107;
        break;
    case 108:
        rtnval = __char_lstart_108;
        break;
    case 109:
        rtnval = __char_lstart_109;
        break;
    case 110:
        rtnval = __char_lstart_110;
        break;
    case 111:
        rtnval = __char_lstart_111;
        break;
    case 112:
        rtnval = __char_lstart_112;
        break;
    case 113:
        rtnval = __char_lstart_113;
        break;
    case 114:
        rtnval = __char_lstart_114;
        break;
    case 115:
        rtnval = __char_lstart_115;
        break;
    case 116:
        rtnval = __char_lstart_116;
        break;
    case 117:
        rtnval = __char_lstart_117;
        break;
    case 118:
        rtnval = __char_lstart_118;
        break;
    case 119:
        rtnval = __char_lstart_119;
        break;
    case 120:
        rtnval = __char_lstart_120;
        break;
    case 121:
        rtnval = __char_lstart_121;
        break;
    case 122:
        rtnval = __char_lstart_122;
        break;
    case 123:
        rtnval = __char_lstart_123;
        break;
    case 124:
        rtnval = __char_lstart_124;
        break;
    case 125:
        rtnval = __char_lstart_125;
        break;
    case 126:
        rtnval = __char_lstart_126;
        break;
    case 127:
        rtnval = __char_lstart_127;
        break;
    case 128:
        rtnval = __char_lstart_128;
        break;
    case 129:
        rtnval = __char_lstart_129;
        break;
    case 130:
        rtnval = __char_lstart_130;
        break;
    case 131:
        rtnval = __char_lstart_131;
        break;
    case 132:
        rtnval = __char_lstart_132;
        break;
    case 133:
        rtnval = __char_lstart_133;
        break;
    case 134:
        rtnval = __char_lstart_134;
        break;
    case 135:
        rtnval = __char_lstart_135;
        break;
    case 136:
        rtnval = __char_lstart_136;
        break;
    case 137:
        rtnval = __char_lstart_137;
        break;
    case 138:
        rtnval = __char_lstart_138;
        break;
    case 139:
        rtnval = __char_lstart_139;
        break;
    case 140:
        rtnval = __char_lstart_140;
        break;
    case 141:
        rtnval = __char_lstart_141;
        break;
    case 142:
        rtnval = __char_lstart_142;
        break;
    case 143:
        rtnval = __char_lstart_143;
        break;
    case 144:
        rtnval = __char_lstart_144;
        break;
    case 145:
        rtnval = __char_lstart_145;
        break;
    case 146:
        rtnval = __char_lstart_146;
        break;
    case 147:
        rtnval = __char_lstart_147;
        break;
    case 148:
        rtnval = __char_lstart_148;
        break;
    case 149:
        rtnval = __char_lstart_149;
        break;
    case 150:
        rtnval = __char_lstart_150;
        break;
    case 151:
        rtnval = __char_lstart_151;
        break;
    case 152:
        rtnval = __char_lstart_152;
        break;
    case 153:
        rtnval = __char_lstart_153;
        break;
    case 154:
        rtnval = __char_lstart_154;
        break;
    case 155:
        rtnval = __char_lstart_155;
        break;
    case 156:
        rtnval = __char_lstart_156;
        break;
    case 157:
        rtnval = __char_lstart_157;
        break;
    case 158:
        rtnval = __char_lstart_158;
        break;
    case 159:
        rtnval = __char_lstart_159;
        break;
    case 160:
        rtnval = __char_lstart_160;
        break;
    case 161:
        rtnval = __char_lstart_161;
        break;
    case 162:
        rtnval = __char_lstart_162;
        break;
    case 163:
        rtnval = __char_lstart_163;
        break;
    case 164:
        rtnval = __char_lstart_164;
        break;
    case 165:
        rtnval = __char_lstart_165;
        break;
    case 166:
        rtnval = __char_lstart_166;
        break;
    case 167:
        rtnval = __char_lstart_167;
        break;
    case 168:
        rtnval = __char_lstart_168;
        break;
    case 169:
        rtnval = __char_lstart_169;
        break;
    case 170:
        rtnval = __char_lstart_170;
        break;
    case 171:
        rtnval = __char_lstart_171;
        break;
    case 172:
        rtnval = __char_lstart_172;
        break;
    case 173:
        rtnval = __char_lstart_173;
        break;
    case 174:
        rtnval = __char_lstart_174;
        break;
    case 175:
        rtnval = __char_lstart_175;
        break;
    case 176:
        rtnval = __char_lstart_176;
        break;
    default: /* Character not printable */
break;
    }
    return rtnval;
}


int get_char_graphic_height(char char_to_place){
    int rtnval = 0;
    switch(char_to_place){
    case 33:
        rtnval = __char_height_33;
        break;
    case 34:
        rtnval = __char_height_34;
        break;
    case 35:
        rtnval = __char_height_35;
        break;
    case 36:
        rtnval = __char_height_36;
        break;
    case 37:
        rtnval = __char_height_37;
        break;
    case 38:
        rtnval = __char_height_38;
        break;
    case 39:
        rtnval = __char_height_39;
        break;
    case 40:
        rtnval = __char_height_40;
        break;
    case 41:
        rtnval = __char_height_41;
        break;
    case 42:
        rtnval = __char_height_42;
        break;
    case 43:
        rtnval = __char_height_43;
        break;
    case 44:
        rtnval = __char_height_44;
        break;
    case 45:
        rtnval = __char_height_45;
        break;
    case 46:
        rtnval = __char_height_46;
        break;
    case 47:
        rtnval = __char_height_47;
        break;
    case 48:
        rtnval = __char_height_48;
        break;
    case 49:
        rtnval = __char_height_49;
        break;
    case 50:
        rtnval = __char_height_50;
        break;
    case 51:
        rtnval = __char_height_51;
        break;
    case 52:
        rtnval = __char_height_52;
        break;
    case 53:
        rtnval = __char_height_53;
        break;
    case 54:
        rtnval = __char_height_54;
        break;
    case 55:
        rtnval = __char_height_55;
        break;
    case 56:
        rtnval = __char_height_56;
        break;
    case 57:
        rtnval = __char_height_57;
        break;
    case 58:
        rtnval = __char_height_58;
        break;
    case 59:
        rtnval = __char_height_59;
        break;
    case 60:
        rtnval = __char_height_60;
        break;
    case 61:
        rtnval = __char_height_61;
        break;
    case 62:
        rtnval = __char_height_62;
        break;
    case 63:
        rtnval = __char_height_63;
        break;
    case 64:
        rtnval = __char_height_64;
        break;
    case 65:
        rtnval = __char_height_65;
        break;
    case 66:
        rtnval = __char_height_66;
        break;
    case 67:
        rtnval = __char_height_67;
        break;
    case 68:
        rtnval = __char_height_68;
        break;
    case 69:
        rtnval = __char_height_69;
        break;
    case 70:
        rtnval = __char_height_70;
        break;
    case 71:
        rtnval = __char_height_71;
        break;
    case 72:
        rtnval = __char_height_72;
        break;
    case 73:
        rtnval = __char_height_73;
        break;
    case 74:
        rtnval = __char_height_74;
        break;
    case 75:
        rtnval = __char_height_75;
        break;
    case 76:
        rtnval = __char_height_76;
        break;
    case 77:
        rtnval = __char_height_77;
        break;
    case 78:
        rtnval = __char_height_78;
        break;
    case 79:
        rtnval = __char_height_79;
        break;
    case 80:
        rtnval = __char_height_80;
        break;
    case 81:
        rtnval = __char_height_81;
        break;
    case 82:
        rtnval = __char_height_82;
        break;
    case 83:
        rtnval = __char_height_83;
        break;
    case 84:
        rtnval = __char_height_84;
        break;
    case 85:
        rtnval = __char_height_85;
        break;
    case 86:
        rtnval = __char_height_86;
        break;
    case 87:
        rtnval = __char_height_87;
        break;
    case 88:
        rtnval = __char_height_88;
        break;
    case 89:
        rtnval = __char_height_89;
        break;
    case 90:
        rtnval = __char_height_90;
        break;
    case 91:
        rtnval = __char_height_91;
        break;
    case 92:
        rtnval = __char_height_92;
        break;
    case 93:
        rtnval = __char_height_93;
        break;
    case 94:
        rtnval = __char_height_94;
        break;
    case 95:
        rtnval = __char_height_95;
        break;
    case 96:
        rtnval = __char_height_96;
        break;
    case 97:
        rtnval = __char_height_97;
        break;
    case 98:
        rtnval = __char_height_98;
        break;
    case 99:
        rtnval = __char_height_99;
        break;
    case 100:
        rtnval = __char_height_100;
        break;
    case 101:
        rtnval = __char_height_101;
        break;
    case 102:
        rtnval = __char_height_102;
        break;
    case 103:
        rtnval = __char_height_103;
        break;
    case 104:
        rtnval = __char_height_104;
        break;
    case 105:
        rtnval = __char_height_105;
        break;
    case 106:
        rtnval = __char_height_106;
        break;
    case 107:
        rtnval = __char_height_107;
        break;
    case 108:
        rtnval = __char_height_108;
        break;
    case 109:
        rtnval = __char_height_109;
        break;
    case 110:
        rtnval = __char_height_110;
        break;
    case 111:
        rtnval = __char_height_111;
        break;
    case 112:
        rtnval = __char_height_112;
        break;
    case 113:
        rtnval = __char_height_113;
        break;
    case 114:
        rtnval = __char_height_114;
        break;
    case 115:
        rtnval = __char_height_115;
        break;
    case 116:
        rtnval = __char_height_116;
        break;
    case 117:
        rtnval = __char_height_117;
        break;
    case 118:
        rtnval = __char_height_118;
        break;
    case 119:
        rtnval = __char_height_119;
        break;
    case 120:
        rtnval = __char_height_120;
        break;
    case 121:
        rtnval = __char_height_121;
        break;
    case 122:
        rtnval = __char_height_122;
        break;
    case 123:
        rtnval = __char_height_123;
        break;
    case 124:
        rtnval = __char_height_124;
        break;
    case 125:
        rtnval = __char_height_125;
        break;
    case 126:
        rtnval = __char_height_126;
        break;
    case 127:
        rtnval = __char_height_127;
        break;
    case 128:
        rtnval = __char_height_128;
        break;
    case 129:
        rtnval = __char_height_129;
        break;
    case 130:
        rtnval = __char_height_130;
        break;
    case 131:
        rtnval = __char_height_131;
        break;
    case 132:
        rtnval = __char_height_132;
        break;
    case 133:
        rtnval = __char_height_133;
        break;
    case 134:
        rtnval = __char_height_134;
        break;
    case 135:
        rtnval = __char_height_135;
        break;
    case 136:
        rtnval = __char_height_136;
        break;
    case 137:
        rtnval = __char_height_137;
        break;
    case 138:
        rtnval = __char_height_138;
        break;
    case 139:
        rtnval = __char_height_139;
        break;
    case 140:
        rtnval = __char_height_140;
        break;
    case 141:
        rtnval = __char_height_141;
        break;
    case 142:
        rtnval = __char_height_142;
        break;
    case 143:
        rtnval = __char_height_143;
        break;
    case 144:
        rtnval = __char_height_144;
        break;
    case 145:
        rtnval = __char_height_145;
        break;
    case 146:
        rtnval = __char_height_146;
        break;
    case 147:
        rtnval = __char_height_147;
        break;
    case 148:
        rtnval = __char_height_148;
        break;
    case 149:
        rtnval = __char_height_149;
        break;
    case 150:
        rtnval = __char_height_150;
        break;
    case 151:
        rtnval = __char_height_151;
        break;
    case 152:
        rtnval = __char_height_152;
        break;
    case 153:
        rtnval = __char_height_153;
        break;
    case 154:
        rtnval = __char_height_154;
        break;
    case 155:
        rtnval = __char_height_155;
        break;
    case 156:
        rtnval = __char_height_156;
        break;
    case 157:
        rtnval = __char_height_157;
        break;
    case 158:
        rtnval = __char_height_158;
        break;
    case 159:
        rtnval = __char_height_159;
        break;
    case 160:
        rtnval = __char_height_160;
        break;
    case 161:
        rtnval = __char_height_161;
        break;
    case 162:
        rtnval = __char_height_162;
        break;
    case 163:
        rtnval = __char_height_163;
        break;
    case 164:
        rtnval = __char_height_164;
        break;
    case 165:
        rtnval = __char_height_165;
        break;
    case 166:
        rtnval = __char_height_166;
        break;
    case 167:
        rtnval = __char_height_167;
        break;
    case 168:
        rtnval = __char_height_168;
        break;
    case 169:
        rtnval = __char_height_169;
        break;
    case 170:
        rtnval = __char_height_170;
        break;
    case 171:
        rtnval = __char_height_171;
        break;
    case 172:
        rtnval = __char_height_172;
        break;
    case 173:
        rtnval = __char_height_173;
        break;
    case 174:
        rtnval = __char_height_174;
        break;
    case 175:
        rtnval = __char_height_175;
        break;
    case 176:
        rtnval = __char_height_176;
        break;
    default: /* Character not printable */
break;
    }
    return rtnval;
}


int get_char_graphic_top(char char_to_place){
    int rtnval = 0;
    switch(char_to_place){
    case 33:
        rtnval = __char_top_33;
        break;
    case 34:
        rtnval = __char_top_34;
        break;
    case 35:
        rtnval = __char_top_35;
        break;
    case 36:
        rtnval = __char_top_36;
        break;
    case 37:
        rtnval = __char_top_37;
        break;
    case 38:
        rtnval = __char_top_38;
        break;
    case 39:
        rtnval = __char_top_39;
        break;
    case 40:
        rtnval = __char_top_40;
        break;
    case 41:
        rtnval = __char_top_41;
        break;
    case 42:
        rtnval = __char_top_42;
        break;
    case 43:
        rtnval = __char_top_43;
        break;
    case 44:
        rtnval = __char_top_44;
        break;
    case 45:
        rtnval = __char_top_45;
        break;
    case 46:
        rtnval = __char_top_46;
        break;
    case 47:
        rtnval = __char_top_47;
        break;
    case 48:
        rtnval = __char_top_48;
        break;
    case 49:
        rtnval = __char_top_49;
        break;
    case 50:
        rtnval = __char_top_50;
        break;
    case 51:
        rtnval = __char_top_51;
        break;
    case 52:
        rtnval = __char_top_52;
        break;
    case 53:
        rtnval = __char_top_53;
        break;
    case 54:
        rtnval = __char_top_54;
        break;
    case 55:
        rtnval = __char_top_55;
        break;
    case 56:
        rtnval = __char_top_56;
        break;
    case 57:
        rtnval = __char_top_57;
        break;
    case 58:
        rtnval = __char_top_58;
        break;
    case 59:
        rtnval = __char_top_59;
        break;
    case 60:
        rtnval = __char_top_60;
        break;
    case 61:
        rtnval = __char_top_61;
        break;
    case 62:
        rtnval = __char_top_62;
        break;
    case 63:
        rtnval = __char_top_63;
        break;
    case 64:
        rtnval = __char_top_64;
        break;
    case 65:
        rtnval = __char_top_65;
        break;
    case 66:
        rtnval = __char_top_66;
        break;
    case 67:
        rtnval = __char_top_67;
        break;
    case 68:
        rtnval = __char_top_68;
        break;
    case 69:
        rtnval = __char_top_69;
        break;
    case 70:
        rtnval = __char_top_70;
        break;
    case 71:
        rtnval = __char_top_71;
        break;
    case 72:
        rtnval = __char_top_72;
        break;
    case 73:
        rtnval = __char_top_73;
        break;
    case 74:
        rtnval = __char_top_74;
        break;
    case 75:
        rtnval = __char_top_75;
        break;
    case 76:
        rtnval = __char_top_76;
        break;
    case 77:
        rtnval = __char_top_77;
        break;
    case 78:
        rtnval = __char_top_78;
        break;
    case 79:
        rtnval = __char_top_79;
        break;
    case 80:
        rtnval = __char_top_80;
        break;
    case 81:
        rtnval = __char_top_81;
        break;
    case 82:
        rtnval = __char_top_82;
        break;
    case 83:
        rtnval = __char_top_83;
        break;
    case 84:
        rtnval = __char_top_84;
        break;
    case 85:
        rtnval = __char_top_85;
        break;
    case 86:
        rtnval = __char_top_86;
        break;
    case 87:
        rtnval = __char_top_87;
        break;
    case 88:
        rtnval = __char_top_88;
        break;
    case 89:
        rtnval = __char_top_89;
        break;
    case 90:
        rtnval = __char_top_90;
        break;
    case 91:
        rtnval = __char_top_91;
        break;
    case 92:
        rtnval = __char_top_92;
        break;
    case 93:
        rtnval = __char_top_93;
        break;
    case 94:
        rtnval = __char_top_94;
        break;
    case 95:
        rtnval = __char_top_95;
        break;
    case 96:
        rtnval = __char_top_96;
        break;
    case 97:
        rtnval = __char_top_97;
        break;
    case 98:
        rtnval = __char_top_98;
        break;
    case 99:
        rtnval = __char_top_99;
        break;
    case 100:
        rtnval = __char_top_100;
        break;
    case 101:
        rtnval = __char_top_101;
        break;
    case 102:
        rtnval = __char_top_102;
        break;
    case 103:
        rtnval = __char_top_103;
        break;
    case 104:
        rtnval = __char_top_104;
        break;
    case 105:
        rtnval = __char_top_105;
        break;
    case 106:
        rtnval = __char_top_106;
        break;
    case 107:
        rtnval = __char_top_107;
        break;
    case 108:
        rtnval = __char_top_108;
        break;
    case 109:
        rtnval = __char_top_109;
        break;
    case 110:
        rtnval = __char_top_110;
        break;
    case 111:
        rtnval = __char_top_111;
        break;
    case 112:
        rtnval = __char_top_112;
        break;
    case 113:
        rtnval = __char_top_113;
        break;
    case 114:
        rtnval = __char_top_114;
        break;
    case 115:
        rtnval = __char_top_115;
        break;
    case 116:
        rtnval = __char_top_116;
        break;
    case 117:
        rtnval = __char_top_117;
        break;
    case 118:
        rtnval = __char_top_118;
        break;
    case 119:
        rtnval = __char_top_119;
        break;
    case 120:
        rtnval = __char_top_120;
        break;
    case 121:
        rtnval = __char_top_121;
        break;
    case 122:
        rtnval = __char_top_122;
        break;
    case 123:
        rtnval = __char_top_123;
        break;
    case 124:
        rtnval = __char_top_124;
        break;
    case 125:
        rtnval = __char_top_125;
        break;
    case 126:
        rtnval = __char_top_126;
        break;
    case 127:
        rtnval = __char_top_127;
        break;
    case 128:
        rtnval = __char_top_128;
        break;
    case 129:
        rtnval = __char_top_129;
        break;
    case 130:
        rtnval = __char_top_130;
        break;
    case 131:
        rtnval = __char_top_131;
        break;
    case 132:
        rtnval = __char_top_132;
        break;
    case 133:
        rtnval = __char_top_133;
        break;
    case 134:
        rtnval = __char_top_134;
        break;
    case 135:
        rtnval = __char_top_135;
        break;
    case 136:
        rtnval = __char_top_136;
        break;
    case 137:
        rtnval = __char_top_137;
        break;
    case 138:
        rtnval = __char_top_138;
        break;
    case 139:
        rtnval = __char_top_139;
        break;
    case 140:
        rtnval = __char_top_140;
        break;
    case 141:
        rtnval = __char_top_141;
        break;
    case 142:
        rtnval = __char_top_142;
        break;
    case 143:
        rtnval = __char_top_143;
        break;
    case 144:
        rtnval = __char_top_144;
        break;
    case 145:
        rtnval = __char_top_145;
        break;
    case 146:
        rtnval = __char_top_146;
        break;
    case 147:
        rtnval = __char_top_147;
        break;
    case 148:
        rtnval = __char_top_148;
        break;
    case 149:
        rtnval = __char_top_149;
        break;
    case 150:
        rtnval = __char_top_150;
        break;
    case 151:
        rtnval = __char_top_151;
        break;
    case 152:
        rtnval = __char_top_152;
        break;
    case 153:
        rtnval = __char_top_153;
        break;
    case 154:
        rtnval = __char_top_154;
        break;
    case 155:
        rtnval = __char_top_155;
        break;
    case 156:
        rtnval = __char_top_156;
        break;
    case 157:
        rtnval = __char_top_157;
        break;
    case 158:
        rtnval = __char_top_158;
        break;
    case 159:
        rtnval = __char_top_159;
        break;
    case 160:
        rtnval = __char_top_160;
        break;
    case 161:
        rtnval = __char_top_161;
        break;
    case 162:
        rtnval = __char_top_162;
        break;
    case 163:
        rtnval = __char_top_163;
        break;
    case 164:
        rtnval = __char_top_164;
        break;
    case 165:
        rtnval = __char_top_165;
        break;
    case 166:
        rtnval = __char_top_166;
        break;
    case 167:
        rtnval = __char_top_167;
        break;
    case 168:
        rtnval = __char_top_168;
        break;
    case 169:
        rtnval = __char_top_169;
        break;
    case 170:
        rtnval = __char_top_170;
        break;
    case 171:
        rtnval = __char_top_171;
        break;
    case 172:
        rtnval = __char_top_172;
        break;
    case 173:
        rtnval = __char_top_173;
        break;
    case 174:
        rtnval = __char_top_174;
        break;
    case 175:
        rtnval = __char_top_175;
        break;
    case 176:
        rtnval = __char_top_176;
        break;
    default: /* Character not printable */
break;
    }
    return rtnval;
}


int get_char_graphic_bottom(char char_to_place){
    int rtnval = 0;
    switch(char_to_place){
    case 33:
        rtnval = __char_bottom_33;
        break;
    case 34:
        rtnval = __char_bottom_34;
        break;
    case 35:
        rtnval = __char_bottom_35;
        break;
    case 36:
        rtnval = __char_bottom_36;
        break;
    case 37:
        rtnval = __char_bottom_37;
        break;
    case 38:
        rtnval = __char_bottom_38;
        break;
    case 39:
        rtnval = __char_bottom_39;
        break;
    case 40:
        rtnval = __char_bottom_40;
        break;
    case 41:
        rtnval = __char_bottom_41;
        break;
    case 42:
        rtnval = __char_bottom_42;
        break;
    case 43:
        rtnval = __char_bottom_43;
        break;
    case 44:
        rtnval = __char_bottom_44;
        break;
    case 45:
        rtnval = __char_bottom_45;
        break;
    case 46:
        rtnval = __char_bottom_46;
        break;
    case 47:
        rtnval = __char_bottom_47;
        break;
    case 48:
        rtnval = __char_bottom_48;
        break;
    case 49:
        rtnval = __char_bottom_49;
        break;
    case 50:
        rtnval = __char_bottom_50;
        break;
    case 51:
        rtnval = __char_bottom_51;
        break;
    case 52:
        rtnval = __char_bottom_52;
        break;
    case 53:
        rtnval = __char_bottom_53;
        break;
    case 54:
        rtnval = __char_bottom_54;
        break;
    case 55:
        rtnval = __char_bottom_55;
        break;
    case 56:
        rtnval = __char_bottom_56;
        break;
    case 57:
        rtnval = __char_bottom_57;
        break;
    case 58:
        rtnval = __char_bottom_58;
        break;
    case 59:
        rtnval = __char_bottom_59;
        break;
    case 60:
        rtnval = __char_bottom_60;
        break;
    case 61:
        rtnval = __char_bottom_61;
        break;
    case 62:
        rtnval = __char_bottom_62;
        break;
    case 63:
        rtnval = __char_bottom_63;
        break;
    case 64:
        rtnval = __char_bottom_64;
        break;
    case 65:
        rtnval = __char_bottom_65;
        break;
    case 66:
        rtnval = __char_bottom_66;
        break;
    case 67:
        rtnval = __char_bottom_67;
        break;
    case 68:
        rtnval = __char_bottom_68;
        break;
    case 69:
        rtnval = __char_bottom_69;
        break;
    case 70:
        rtnval = __char_bottom_70;
        break;
    case 71:
        rtnval = __char_bottom_71;
        break;
    case 72:
        rtnval = __char_bottom_72;
        break;
    case 73:
        rtnval = __char_bottom_73;
        break;
    case 74:
        rtnval = __char_bottom_74;
        break;
    case 75:
        rtnval = __char_bottom_75;
        break;
    case 76:
        rtnval = __char_bottom_76;
        break;
    case 77:
        rtnval = __char_bottom_77;
        break;
    case 78:
        rtnval = __char_bottom_78;
        break;
    case 79:
        rtnval = __char_bottom_79;
        break;
    case 80:
        rtnval = __char_bottom_80;
        break;
    case 81:
        rtnval = __char_bottom_81;
        break;
    case 82:
        rtnval = __char_bottom_82;
        break;
    case 83:
        rtnval = __char_bottom_83;
        break;
    case 84:
        rtnval = __char_bottom_84;
        break;
    case 85:
        rtnval = __char_bottom_85;
        break;
    case 86:
        rtnval = __char_bottom_86;
        break;
    case 87:
        rtnval = __char_bottom_87;
        break;
    case 88:
        rtnval = __char_bottom_88;
        break;
    case 89:
        rtnval = __char_bottom_89;
        break;
    case 90:
        rtnval = __char_bottom_90;
        break;
    case 91:
        rtnval = __char_bottom_91;
        break;
    case 92:
        rtnval = __char_bottom_92;
        break;
    case 93:
        rtnval = __char_bottom_93;
        break;
    case 94:
        rtnval = __char_bottom_94;
        break;
    case 95:
        rtnval = __char_bottom_95;
        break;
    case 96:
        rtnval = __char_bottom_96;
        break;
    case 97:
        rtnval = __char_bottom_97;
        break;
    case 98:
        rtnval = __char_bottom_98;
        break;
    case 99:
        rtnval = __char_bottom_99;
        break;
    case 100:
        rtnval = __char_bottom_100;
        break;
    case 101:
        rtnval = __char_bottom_101;
        break;
    case 102:
        rtnval = __char_bottom_102;
        break;
    case 103:
        rtnval = __char_bottom_103;
        break;
    case 104:
        rtnval = __char_bottom_104;
        break;
    case 105:
        rtnval = __char_bottom_105;
        break;
    case 106:
        rtnval = __char_bottom_106;
        break;
    case 107:
        rtnval = __char_bottom_107;
        break;
    case 108:
        rtnval = __char_bottom_108;
        break;
    case 109:
        rtnval = __char_bottom_109;
        break;
    case 110:
        rtnval = __char_bottom_110;
        break;
    case 111:
        rtnval = __char_bottom_111;
        break;
    case 112:
        rtnval = __char_bottom_112;
        break;
    case 113:
        rtnval = __char_bottom_113;
        break;
    case 114:
        rtnval = __char_bottom_114;
        break;
    case 115:
        rtnval = __char_bottom_115;
        break;
    case 116:
        rtnval = __char_bottom_116;
        break;
    case 117:
        rtnval = __char_bottom_117;
        break;
    case 118:
        rtnval = __char_bottom_118;
        break;
    case 119:
        rtnval = __char_bottom_119;
        break;
    case 120:
        rtnval = __char_bottom_120;
        break;
    case 121:
        rtnval = __char_bottom_121;
        break;
    case 122:
        rtnval = __char_bottom_122;
        break;
    case 123:
        rtnval = __char_bottom_123;
        break;
    case 124:
        rtnval = __char_bottom_124;
        break;
    case 125:
        rtnval = __char_bottom_125;
        break;
    case 126:
        rtnval = __char_bottom_126;
        break;
    case 127:
        rtnval = __char_bottom_127;
        break;
    case 128:
        rtnval = __char_bottom_128;
        break;
    case 129:
        rtnval = __char_bottom_129;
        break;
    case 130:
        rtnval = __char_bottom_130;
        break;
    case 131:
        rtnval = __char_bottom_131;
        break;
    case 132:
        rtnval = __char_bottom_132;
        break;
    case 133:
        rtnval = __char_bottom_133;
        break;
    case 134:
        rtnval = __char_bottom_134;
        break;
    case 135:
        rtnval = __char_bottom_135;
        break;
    case 136:
        rtnval = __char_bottom_136;
        break;
    case 137:
        rtnval = __char_bottom_137;
        break;
    case 138:
        rtnval = __char_bottom_138;
        break;
    case 139:
        rtnval = __char_bottom_139;
        break;
    case 140:
        rtnval = __char_bottom_140;
        break;
    case 141:
        rtnval = __char_bottom_141;
        break;
    case 142:
        rtnval = __char_bottom_142;
        break;
    case 143:
        rtnval = __char_bottom_143;
        break;
    case 144:
        rtnval = __char_bottom_144;
        break;
    case 145:
        rtnval = __char_bottom_145;
        break;
    case 146:
        rtnval = __char_bottom_146;
        break;
    case 147:
        rtnval = __char_bottom_147;
        break;
    case 148:
        rtnval = __char_bottom_148;
        break;
    case 149:
        rtnval = __char_bottom_149;
        break;
    case 150:
        rtnval = __char_bottom_150;
        break;
    case 151:
        rtnval = __char_bottom_151;
        break;
    case 152:
        rtnval = __char_bottom_152;
        break;
    case 153:
        rtnval = __char_bottom_153;
        break;
    case 154:
        rtnval = __char_bottom_154;
        break;
    case 155:
        rtnval = __char_bottom_155;
        break;
    case 156:
        rtnval = __char_bottom_156;
        break;
    case 157:
        rtnval = __char_bottom_157;
        break;
    case 158:
        rtnval = __char_bottom_158;
        break;
    case 159:
        rtnval = __char_bottom_159;
        break;
    case 160:
        rtnval = __char_bottom_160;
        break;
    case 161:
        rtnval = __char_bottom_161;
        break;
    case 162:
        rtnval = __char_bottom_162;
        break;
    case 163:
        rtnval = __char_bottom_163;
        break;
    case 164:
        rtnval = __char_bottom_164;
        break;
    case 165:
        rtnval = __char_bottom_165;
        break;
    case 166:
        rtnval = __char_bottom_166;
        break;
    case 167:
        rtnval = __char_bottom_167;
        break;
    case 168:
        rtnval = __char_bottom_168;
        break;
    case 169:
        rtnval = __char_bottom_169;
        break;
    case 170:
        rtnval = __char_bottom_170;
        break;
    case 171:
        rtnval = __char_bottom_171;
        break;
    case 172:
        rtnval = __char_bottom_172;
        break;
    case 173:
        rtnval = __char_bottom_173;
        break;
    case 174:
        rtnval = __char_bottom_174;
        break;
    case 175:
        rtnval = __char_bottom_175;
        break;
    case 176:
        rtnval = __char_bottom_176;
        break;
    default: /* Character not printable */
break;
    }
    return rtnval;
}


