/* Autogenerated header file to write OTF and TTF files into const memory for inclusion into applciations */
#ifndef __OTF_CONST_HELVETICALTSTD_H
#define __OTF_CONST_HELVETICALTSTD_H
#define HELVETICALTSTD	1

#define OTF_HELVETICALTSTD_LEN   27720
extern const uint8_t HelveticaLtStd_const[OTF_HELVETICALTSTD_LEN];
#endif


