/* Autogenerated header file to write OTF and TTF files into const memory for inclusion into applciations */
#ifndef __OTF_CONST_SOURCESANSPRO_LIGHT_H
#define __OTF_CONST_SOURCESANSPRO_LIGHT_H
#define SOURCESANSPRO_LIGHT	1

#define OTF_SOURCESANSPRO_LIGHT_LEN   230688
extern const uint8_t SourceSansPro_Light_const[OTF_SOURCESANSPRO_LIGHT_LEN];
#endif


