/* Autogenerated header file to write OTF and TTF files into const memory for inclusion into applciations */
#ifndef __OTF_CONST_SOURCESANSPRO_REGULAR_H
#define __OTF_CONST_SOURCESANSPRO_REGULAR_H
#define SOURCESANSPRO_REGULAR	1

#define OTF_SOURCESANSPRO_REGULAR_LEN   234960
extern const uint8_t SourceSansPro_Regular_const[OTF_SOURCESANSPRO_REGULAR_LEN];
#endif


